services:
  # --- EL PROXY INVERSO ---
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: local-proxy
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy-data:/data
      - ./proxy-letsencrypt:/etc/letsencrypt
    restart: always

  # 1. Tu bot monitor
  scraper-bot:
    build: ./scraper-bot
    container_name: local-scraper-bot
    volumes:
      - ./scraper-bot:/app
    env_file:
      - ./scraper-bot/.env
    restart: always

  # 2. Tu bot hunter
  wallapop-hunter:
    build: ./wallapop-hunter
    container_name: local-wallapop-hunter
    volumes:
      - ./wallapop-hunter:/app
    env_file:
      - ./wallapop-hunter/.env
    restart: always

  # 3. Selenium adaptado para Apple Silicon
  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: local-selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    restart: always

# 4. Uptime Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: local-uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - "3001:3001"

  # 5. Portainer Local
  portainer:
    image: portainer/portainer-ce:latest
    container_name: local-portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: always
    ports:
      - "9002:9000"

  # --- El NUEVO COMPONENTE: PI-HOLE (DNS & Bloqueador) ---
# --- PI-HOLE ---
  pihole:
    image: pihole/pihole:latest
    container_name: local-dns-pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Madrid'
      # 🔑 Esta es la nueva variable oficial para Pi-hole v6:
      FTLCONF_webserver_api_password: '${PIHOLE_FTL_PASSWORD}'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: always

volumes:
  uptime-kuma-data:
  portainer-data:
