version: '3.8'

services:
  # 1. Tu Bot de Wallapop
  wallapop-hunter:
    build: ./wallapop-hunter
    container_name: wallapop-hunter
    restart: unless-stopped
    # env_file: ./wallapop-hunter/.env 

  # 2. Tu Scraper (Vuelos/BOE)
  scraper-bot:
    build: ./scraper-bot
    container_name: scraper-bot
    restart: unless-stopped
    
  # 3. Monitorización (Uptime Kuma)
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    # 👇 Añade esta línea mágica:
    profiles: ["monitor"] 
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
# 4. El Capitán del Barco (Portainer)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Vital: Le da permiso para controlar Docker
      - portainer_data:/data                        # 👈 Donde guarda tus claves y usuarios
volumes:
  uptime-kuma-data:
  portainer_data: