version: '3.8'

services:
  inap-sniper:
    build: . 
    container_name: inap-sniper
    restart: unless-stopped
    
    # MAGIA: Le decimos que cargue el archivo .env
    env_file:
      - .env
      
    # Opcional: Si quieres ser explícito, puedes dejarlas así.
    # Docker sustituirá ${TELEGRAM_TOKEN} por lo que haya en el .env
    environment:
      - TZ=${TZ}
      - TARGET_URL=${TARGET_URL}
      - SEARCH_TEXT=${SEARCH_TEXT}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - EMAIL_USER=${EMAIL_USER}
      - APP_EMAIL_PASSWORD=${APP_EMAIL_PASSWORD}
      
    volumes:
      - ./registros:/app/logs